### ISSUE TITLE
number of identical games for sale

### ISSUE THREAD

**Issue by Le-zOU** [halver94/Scrapy#4]
can we have the information about the number of identical games on sale

exemple: https://www.okkazeo.com/jeux/view/44398 : 10 offers

**Comment by halver94** [comment]
I'm trying to keep essential informations on display and this one can be easily found by typing the name of the game in the search bar.
One thing that I can do is, like the seller, add a button to directly filter on the name of the game.

One thing is that sometimes on okkazeo, for the same game, you will have different names.

**Comment by halver94** [comment]
A quickfilter has been added like the one for the vendor
