### ISSUE TITLE
add a "mark as seen"/"hide" option

### ISSUE THREAD

**Issue by Le-zOU** [halver94/Scrapy#5]
when filtering by best deals, it's always the same offers at the top, forcing the user to scroll down to see the actual new offers

Could we have an option to "hide" offers so they don't get displayed any longer ?
And of course an option to see only the hidden offers and unhide them.

Thank you

**Comment by halver94** [comment]
This one would requiers some heavy rework on the backend and some kind of state per user. The serve keeps very low state right and handling client account seems overkill.
I've added a date filter so that users can search in the last X days.
